package server

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"webtyp.com/router/routescan"
)

// GeneratedMainDir is the directory, relative to the project root, holding the
// generated server entry point. It must be inside the project: outside the
// module tree the Go toolchain cannot resolve the project's own imports.
const (
	GeneratedMainDir      = ".build/server"
	GeneratedMainFilename = "main.go"
	GitIgnoreFile         = ".gitignore"
	BuildDirGitIgnore     = ".build/"
)

// MainConfig is what the generated main hardcodes.
type MainConfig struct {
	Port      string
	PublicDir string
	DevTLS    bool // dev only; production uses AutoCert or Cert/Key
}

type mainTemplateData struct {
	ModulePath   string
	Port         string
	PublicDir    string
	DevTLS       bool
	RegisterArgs string
}

const mainTemplateText = `//go:build !wasm

// Code generated by webtyp.com/server. DO NOT EDIT.
package main

import (
	"log"
	"{{.ModulePath}}/routes"
	"webtyp.com/server/httpd"
)

func main() {
	s := httpd.New(httpd.Config{
		Port:      "{{.Port}}",
		PublicDir: "{{.PublicDir}}",
		Gzip:      true,
		Health:    true,
		TLS:       httpd.TLSConfig{DevTLS: {{.DevTLS}}},
	})
	routes.Register({{.RegisterArgs}})
	if err := s.ListenAndServe(); err != nil {
		log.Fatal(err)
	}
}
`

// HasRoutes reports whether the project declares routes and therefore needs a
// compiled server process.
func HasRoutes(rootDir string) bool {
	routesFile := filepath.Join(rootDir, routescan.DefaultFile)
	_, err := os.Stat(routesFile)
	return err == nil
}

func readModulePath(rootDir string) string {
	content, err := os.ReadFile(filepath.Join(rootDir, "go.mod"))
	if err != nil {
		return filepath.Base(rootDir)
	}
	lines := strings.Split(string(content), "\n")
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "module ") || strings.HasPrefix(line, "module\t") {
			fields := strings.Fields(line)
			if len(fields) >= 2 {
				return fields[1]
			}
		}
	}
	return filepath.Base(rootDir)
}

// GenerateMain writes the server entry point for the project at rootDir and
// returns the absolute path of the written file.
//
// modulePath is the project's module path, read from go.mod.
func GenerateMain(rootDir, modulePath string, cfg MainConfig) (string, error) {
	outDir := filepath.Join(rootDir, GeneratedMainDir)
	if err := os.MkdirAll(outDir, 0755); err != nil {
		return "", fmt.Errorf("creating build directory: %w", err)
	}

	mainFile := filepath.Join(outDir, GeneratedMainFilename)
	absPath, err := filepath.Abs(mainFile)
	if err != nil {
		return "", fmt.Errorf("resolving absolute path: %w", err)
	}

	routesFile := filepath.Join(rootDir, routescan.DefaultFile)
	registerArgs := detectRegisterArgs(routesFile)

	data := mainTemplateData{
		ModulePath:   modulePath,
		Port:         cfg.Port,
		PublicDir:    cfg.PublicDir,
		DevTLS:       cfg.DevTLS,
		RegisterArgs: registerArgs,
	}

	tmpl, err := template.New("main").Parse(mainTemplateText)
	if err != nil {
		return "", fmt.Errorf("parsing main template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("executing main template: %w", err)
	}

	if err := os.WriteFile(absPath, buf.Bytes(), 0644); err != nil {
		return "", fmt.Errorf("writing generated main file: %w", err)
	}

	_ = ensureGitIgnore(rootDir, BuildDirGitIgnore)

	return absPath, nil
}

func detectRegisterArgs(routesFile string) string {
	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, routesFile, nil, 0)
	if err != nil {
		return "s.Router()"
	}

	var targetFunc *ast.FuncDecl
	for _, decl := range node.Decls {
		fn, ok := decl.(*ast.FuncDecl)
		if !ok || fn.Type == nil || fn.Type.Params == nil {
			continue
		}
		if fn.Name.Name == "Register" {
			targetFunc = fn
			break
		}
		if targetFunc == nil && len(fn.Type.Params.List) > 0 {
			if isRouterParam(fn.Type.Params.List[0].Type) {
				targetFunc = fn
			}
		}
	}

	if targetFunc == nil {
		return "s.Router()"
	}

	paramCount := 0
	for _, field := range targetFunc.Type.Params.List {
		if len(field.Names) == 0 {
			paramCount++
		} else {
			paramCount += len(field.Names)
		}
	}

	if paramCount <= 1 {
		return "s.Router()"
	}

	args := make([]string, paramCount)
	args[0] = "s.Router()"
	for i := 1; i < paramCount; i++ {
		args[i] = "nil"
	}
	return strings.Join(args, ", ")
}

func isRouterParam(expr ast.Expr) bool {
	sel, ok := expr.(*ast.SelectorExpr)
	if !ok {
		return false
	}
	ident, ok := sel.X.(*ast.Ident)
	if !ok {
		return false
	}
	return (ident.Name == "router" || ident.Name == "Router") && sel.Sel.Name == "Router"
}

func ensureGitIgnore(rootDir, entry string) error {
	ignorePath := filepath.Join(rootDir, GitIgnoreFile)
	content, err := os.ReadFile(ignorePath)
	if err == nil {
		lines := strings.Split(string(content), "\n")
		for _, line := range lines {
			if strings.TrimSpace(line) == strings.TrimSpace(entry) {
				return nil
			}
		}
		if !strings.HasSuffix(string(content), "\n") {
			content = append(content, '\n')
		}
		content = append(content, []byte(entry+"\n")...)
		return os.WriteFile(ignorePath, content, 0644)
	}

	if os.IsNotExist(err) {
		return os.WriteFile(ignorePath, []byte(entry+"\n"), 0644)
	}
	return err
}
